<?php

/**
 * Implementation of hook_init()
 */
function login_shadowbox_init() {

  $enable = variable_get('login_shadowbox_enabled', FALSE) && variable_get('shadowbox_enabled', TRUE);

  if(user_is_anonymous() && $enable) {

    $login_path = drupal_get_path_alias('user/login');

    $block = module_invoke('user', 'block_view', 'login');

    $login_form = '<div id="shadowbox_login">';
    $login_form .= render($block);
    $login_form .= '</div>';

    $shadowbox_login_settings = array (
      'loginPath' => $login_path,
      'loginForm' => $login_form,
      'width'     => variable_get('login_shadowbox_width', 300),
      'height'    => variable_get('login_shadowbox_height', 400),
      'modal'     => variable_get('login_shadowbox_modal', TRUE),
    );

    // Login block is blank in some paths so we check that before adding js and css files
    if (isset($block['content']) && $block['content']) {
      // we have to be sure shadowbox is loaded in case it is not
      drupal_add_library('shadowbox', 'shadowbox');
      // add the neccessary javascript and css files needed by shadowbox login
      $path = drupal_get_path('module', 'login_shadowbox');
      drupal_add_js(array('shadowboxLogin' => $shadowbox_login_settings), 'setting');
      drupal_add_js($path . '/scripts/login_shadowbox.js');
      $css_path = variable_get('login_shadowbox_css', $path . '/css/login_shadowbox.css');
      drupal_add_css($css_path, array('group' => 'CSS_THEME'));
    }

  }
}

/**
 * Implementation of hook_menu()
 */
function login_shadowbox_menu() {
  $items = array();

  $items['admin/config/media/shadowbox/login'] = array(
    'title' => 'Login',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('login_shadowbox_settings'),
    'access arguments' => array('administer shadowbox login'),
    'description' => 'Configure the Shadowbox login settings.',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
    'file' => 'login_shadowbox.admin.inc',
  );

  return $items;

}

/**
 * Implmentation of hook_permission()
 */
function login_shadowbox_permission() {
  return array (
    'administer shadowbox login' => array (
      'title' => t('Administer shadowbox login'),
      'description' => t('Allows users to change the settings for the Shadowbox Login module'),
    )
  );
}

/**
 * Implementation of hook_block_info()
 */
function login_shadowbox_block_info() {
  $blocks['login_shadowbox_login_block'] = array (
    'info' => t('Shadowbox Login Link'),
    'cache' => DRUPAL_NO_CACHE,
    'visibility' => 0,
    'pages' => array('user/login'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view()
 */
function login_shadowbox_block_view($delta = '') {
  if($delta == 'login_shadowbox_login_block' && user_is_anonymous() && !(arg(0) == 'user' && !is_numeric(arg(1)))) {
    $block['subject'] = t('Login');
    $block['content'] = l(t('Login'), 'user/login');
    return $block;
  }
}
